name: artifact
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu124
      - torch==2.5.1+cu124
      - accelerate==1.13.0
      - transformers==4.49.0
      - qwen-vl-utils==0.0.8
      - fastapi==0.136.1
      - uvicorn==0.46.0
      - python-multipart==0.0.27
      - opencv-contrib-python==4.11.0.86
      - mediapipe
      - numpy==1.26.4
      - pillow==12.1.1
